### ISSUE TITLE
Great tool! A little question on the KITTI dataset

### ISSUE THREAD

**Issue by Sibozhu** [nalinraut/3D-Points-on-Image#1]
Hey @nalinraut Thanks for making this great tool for visualizing 3D pointcloud overlays on images. It's really helpful and I'd like to use and cite it in my research. 

One little question, for which specific KITTI dataset are you using for this tool by default? I'm trying to do the overlay on [KITTI 3D Object Detection Dataset](http://www.cvlibs.net/datasets/kitti/eval_object.php?obj_benchmark=3d) but seems hard to find the calibration files in the same format.

Best,
Sibo Zhu

**Comment by Sibozhu** [comment]
Specifically, how did you get the `C51_LidarPts_0000.dat` point cloud data format? I see all the point cloud from KITTI are in .bin format.

**Comment by nalinraut** [comment]
@Sibozhu, This was an assignment from one of my internship and the dataset had `.dat` format. Does `.bin` not work with the utility tool provided?

**Comment by Sibozhu** [comment]
I just realized the calibration format was meant for the RAW_DATASET section of KITTI. it's actually a bit different from the calibration file in the detection dataset. Guess further development are needed to have it compile with detection section (we want to use data in the detection section because it has a lot of bounding box label)

I guess I can close this issue now. Thank you @nalinraut!
